-- Sets Database Schema path
USE legos.legos;

-- Add primary keys
ALTER TABLE COLORS ADD PRIMARY KEY (ID);
ALTER TABLE INVENTORIES ADD PRIMARY KEY (ID);s
ALTER TABLE PARTS ADD PRIMARY KEY (PART_NUM);
ALTER TABLE PART_CATEGORIES ADD PRIMARY KEY (ID);
ALTER TABLE SETS ADD PRIMARY KEY (SET_NUM);
ALTER TABLE THEMES ADD PRIMARY KEY (ID);

-- Add foreign keys
ALTER TABLE INVENTORY_PARTS ADD FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORIES(ID);
ALTER TABLE INVENTORY_PARTS ADD FOREIGN KEY (PART_NUM) REFERENCES PARTS(PART_NUM);
ALTER TABLE INVENTORY_PARTS ADD FOREIGN KEY (COLOR_ID) REFERENCES COLORS(ID);

ALTER TABLE PARTS ADD FOREIGN KEY (PART_CAT_ID) REFERENCES PART_CATEGORIES(ID);

ALTER TABLE INVENTORY_SETS ADD FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORIES(ID);
ALTER TABLE INVENTORY_SETS ADD FOREIGN KEY (SET_NUM) REFERENCES SETS(SET_NUM);

ALTER TABLE SETS ADD FOREIGN KEY (THEME_ID) REFERENCES THEMES(ID);

ALTER TABLE INVENTORIES ADD FOREIGN KEY (SET_NUM) REFERENCES SETS(SET_NUM);